version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_ROOT_PASSWORD: 'dbpassword'
      MYSQL_DATABASE: 'dbname'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    tty: true

  app:
      build: .
      container_name: app
      ports:
        - '8080:8080'
      volumes:
        - .:/code
      environment:
        ENV: 'development'
        HTTP_PORT: 8080
      depends_on:
        - db
      tty: true
